### ISSUE TITLE
Error while connecting

### ISSUE THREAD

**Issue by jakobroehrl** [eneiluj/integration_dropbox#1]
I get this message when I try to connect to dropbox 

This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit.

**Comment by eneiluj** [comment]
Thanks for the feedback. It's weird because in the app analytics on Dropbox I just see 2 users (most likely you and me :grin:). There must be a problem on Dropbox side. I'll check that.

In the meantime, it's quick and easy to create your own Dropbox OAuth app. Follow the instructions in the connected accounts admin settings section.

**Comment by eneiluj** [comment]
@jakobroehrl The limit in my dropbox app config was set to 1... It's now 500. I tried with another account and it works fine. Could you try again?

Thanks a lot for the feedback.

**Comment by jakobroehrl** [comment]
Yes, sure. 
With the 0.0.2 version it's working, thanks a lot! :)
